=== grgrzybek/osgi-packages/metadata/osgi.specs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
-->

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://github.com/grgrzybek/osgi-packages/1"
        xmlns:tns="https://github.com/grgrzybek/osgi-packages/1"
        version="1.0" elementFormDefault="qualified">

    <element name="specifications" type="tns:specificationsType" />

    <complexType name="specificationsType">
        <sequence>
            <element minOccurs="0" maxOccurs="unbounded" name="spec" type="tns:specType" />
        </sequence>
    </complexType>

    <complexType name="specType">
        <annotation>
            <documentation>Specification is entire document (like Core or Compendium)</documentation>
        </annotation>
        <sequence>
            <element name="item" type="tns:itemType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="id">
            <annotation>
                <documentation>Identifier of the specification (core, enterprise, compendium, ...)</documentation>
            </annotation>
            <simpleType>
                <restriction base="string">
                    <enumeration value="core" />
                    <enumeration value="compendium" />
                    <enumeration value="enterprise" />
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="itemType">
        <annotation>
            <documentation>
                An item a chapter from any of OSGi specification documents.
                A chapter generally introduces some Java packages (which are the main concept of this project).
                Recently, chapter numbers were consistent, like "126. JNDI Services Specification", but it wasn't
                the case in earlier versions.
                Also for core specification, not every chapter defines unique packages.
            </documentation>
        </annotation>
        <sequence>
            <element name="description" type="string">
                <annotation>
                    <documentation>If some chapters describe the same packages, descriptor provides some clarification.</documentation>
                </annotation>
            </element>
            <element name="package" type="tns:packageType" minOccurs="0" maxOccurs="unbounded" />
            <element name="notes" type="tns:notesType" minOccurs="0" />
        </sequence>
        <attribute name="number" type="integer">
            <annotation>
                <documentation>
                    Chapter number from specification PDF. If the chapter number is different across specification versions,
                    a number from latest specification version is used.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="title" type="string">
            <annotation>
                <documentation>Chapter title from specification PDF.</documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="packageType">
        <annotation>
            <documentation>
                An OSGi package is unique Java package identifier. It has versions specified for each
                OSGi specification version.
            </documentation>
        </annotation>
        <sequence>
            <element name="version" type="tns:versionType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="id" type="string">
            <annotation>
                <documentation>Unique Java package name</documentation>
            </annotation>
        </attribute>
        <attribute name="ref-id" type="string">
            <annotation>
                <documentation>Unique Java package name reference - if package is defined (also) in different chapter</documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="versionType">
        <annotation>
            <documentation>
                OSGi package has unique version both in OSGi specification and in given Maven artifact
            </documentation>
        </annotation>
        <sequence>
            <element name="note" type="tns:noteType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="id" type="string"></attribute>
        <attribute name="spec" type="string"></attribute>
    </complexType>

    <complexType name="notesType">
        <annotation>
            <documentation>Additional information related to given "item"</documentation>
        </annotation>
        <sequence>
            <element name="note" type="tns:noteType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="noteType">
        <annotation>
            <documentation>
                A note may refer (by some pointer) to part of generated information to restrict, clarify or alter
                some information extracted from Maven artifacts
            </documentation>
        </annotation>
        <simpleContent>
            <extension base="string">
                <attribute name="ref" type="string" />
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== grgrzybek/osgi-packages/metadata/osgi.specs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
-->
<!--
    The information is extracted from specification documents from https://osgi.org site.
    This file is *not* generated.
    The information is intended to be merged/combined with the generated XMLs, related to content of OSGi
    artifacts from Maven Central.
-->
<specifications xmlns="https://github.com/grgrzybek/osgi-packages/1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://github.com/grgrzybek/osgi-packages/1 osgi.specs.xsd">

    <spec id="core">
        <item number="4" title="Lifecycle Layer">
            <description>Framework Specification (Lifecycle Layer) and Framework Launching</description>
            <package ref-id="org.osgi.framework" />
            <package ref-id="org.osgi.framework.launch" />
        </item>
        <item number="5" title="Service Layer">
            <description>Framework Specification (Service Layer)</description>
            <package ref-id="org.osgi.framework" />
        </item>
        <item number="6" title="Resource API Specification">
            <description>API for the generic Requirement-Capability model</description>
            <package id="org.osgi.resource">
                <version id="1.0" spec="7.0.0" />
                <version id="1.0" spec="6.0.0" />
                <version id="1.0" spec="5.0.0" />
            </package>
        </item>
        <item number="7" title="Bundle Wiring API Specification">
            <description>API to introspect the wiring between the requirements and capabilities of resolved bundles.</description>
            <package id="org.osgi.framework.wiring">
                <version id="1.2" spec="7.0.0" />
                <version id="1.2" spec="6.0.0" />
                <version id="1.1" spec="5.0.0" />
                <version id="1.0" spec="4.3.0" />
            </package>
        </item>
        <item number="7" title="Package Admin Service Specification">
            <description>The Package Admin service provides an interface to let the Management Agent make the decision regarding any shared packages when the exporting bundle is uninstalled or updated.</description>
            <package id="org.osgi.service.packageadmin">
                <version id="1.2" spec="4.2.0" />
                <version id="1.2" spec="4.1.0" />
                <version id="1.2" spec="4.0.1" />
                <version id="1.2" spec="4.0.0" />
                <version id="1.1" spec="3.0.0">
                    <note>In 3.0.0 specification, `org.osgi.service.packageadmin` package is specified in chapter 5</note>
                </version>
                <version id="1.0" spec="2.0.0">
                    <note>In 2.0.0 specification, `org.osgi.service.packageadmin` package is specified in chapter 3</note>
                </version>
            </package>
            <notes>
                <note>After 4.2.0 specification, `org.osgi.service.packageadmin` package is no longer specified</note>
            </notes>
        </item>
        <item number="8" title="Framework Namespaces Specification">
            <description>A Namespace defines the semantics of a Requirement-Capability pair.</description>
            <package id="org.osgi.framework.namespace">
                <version id="1.1" spec="7.0.0" />
                <version id="1.1" spec="6.0.0" />
                <version id="1.0" spec="5.0.0" />
            </package>
        </item>
        <item number="8" title="Start Level Service Specification">
            <description>This specification describes how to enable a Management Agent to control the relative starting and stopping order of bundles in an OSGi Service Platform.</description>
            <package id="org.osgi.service.startlevel">
                <version id="1.1" spec="4.2.0" />
                <version id="1.1" spec="4.1.0" />
                <version id="1.0" spec="4.0.1" />
                <version id="1.0" spec="4.0.0" />
                <version id="1.0" spec="3.0.0">
                    <note>In 3.0.0 specification, `org.osgi.service.startlevel` package is specified in chapter 6</note>
                </version>
            </package>
            <notes>
                <note>After 4.2.0 specification, `org.osgi.service.startlevel` service functionality is moved to `org.osgi.framework.startlevel` API</note>
            </notes>
        </item>
        <item number="9" title="Start Level API Specification">
            <description>This specification describes how to enable a management agent to control the relative starting and stopping order of bundles in an OSGi framework.</description>
            <package id="org.osgi.framework.startlevel">
                <version id="1.0" spec="7.0.0" />
                <version id="1.0" spec="6.0.0" />
                <version id="1.0" spec="5.0.0" />
                <version id="1.0" spec="4.3.0">
                    <note>In 4.3.0 specification, `org.osgi.framework.startlevel` package is specified in chapter 8</note>
                </version>
            </package>
        </item>
        <item number="10" title="Framework API">
            <description>Framework Specification (Lifecycle Layer and Service Layer), Framework Launching, OSGi Versioning Annotations Package, OSGi Bundle Annotations Package</description>
            <package id="org.osgi.framework">
                <version id="1.9" spec="7.0.0" />
                <version id="1.8" spec="6.0.0" />
                <version id="1.7" spec="5.0.0" />
                <version id="1.6" spec="4.3.0" />
                <version id="1.5" spec="4.2.0" />
                <version id="1.4" spec="4.1.0" />
                <version id="1.3" spec="4.0.1" />
                <version id="1.3" spec="4.0.0" />
                <version id="1.2" spec="3.0.0" />
                <version id="1.1" spec="2.0.0" />
            </package>
            <package id="org.osgi.framework.launch">
                <version id="1.2" spec="7.0.0" />
                <version id="1.2" spec="6.0.0" />
                <version id="1.1" spec="5.0.0" />
                <version id="1.0" spec="4.3.0" />
                <version id="1.0" spec="4.2.0" />
            </package>
            <package ref-id="org.osgi.resource" />
            <package ref-id="org.osgi.framework.wiring" />
            <package ref-id="org.osgi.framework.startlevel" />
            <package ref-id="org.osgi.framework.namespace" />
            <package id="org.osgi.annotation.versioning">
                <version id="1.1" spec="7.0.0" />
                <version id="1.0" spec="6.0.0" />
            </package>
            <package id="org.osgi.annotation.bundle">
                <version id="1.0" spec="7.0.0" />
            </package>
        </item>
        <item number="24" title="Jini Driver Service Specification">
            <description>This specification outlines the rules for using Jini in an OSGi Service Platform.</description>
            <package id="org.osgi.service.jini">
                <version id="1.0" spec="3.0.0" />
            </package>
        </item>
        <item number="50" title="Conditional Permission Admin Service Specification">
            <description>This specification adds several new features to the Java permission model to adapt it to the typical use cases of OSGi deployments.</description>
            <package id="org.osgi.service.condpermadmin">
                <version id="1.1" spec="7.0.0" />
                <version id="1.1" spec="6.0.0" />
                <version id="1.1" spec="5.0.0" />
                <version id="1.1" spec="4.3.0" />
                <version id="1.1" spec="4.2.0" />
                <version id="1.0" spec="4.1.0" />
                <version id="1.0" spec="4.0.1" />
                <version id="1.0" spec="4.0.0" />
            </package>
            <notes>
                <note>Until 4.2.0 specification, `org.osgi.service.condpermadmin` package is specified in chapter 9</note>
            </notes>
        </item>
        <item number="51" title="Permission Admin Service Specification">
            <description>Permission Admin service used to administrate the permissions of a bundle and provide defaults for all bundles.</description>
            <package id="org.osgi.service.permissionadmin">
                <version id="1.2" spec="7.0.0" />
                <version id="1.2" spec="6.0.0" />
                <version id="1.2" spec="5.0.0" />
                <version id="1.2" spec="4.3.0" />
                <version id="1.2" spec="4.2.0" />
                <version id="1.2" spec="4.1.0" />
                <version id="1.2" spec="4.0.1" />
                <version id="1.2" spec="4.0.0" />
                <version id="1.1" spec="3.0.0">
                    <note>In 3.0.0 specification, `org.osgi.service.permissionadmin` package is specified in chapter 7</note>
                </version>
                <version id="1.0" spec="2.0.0">
                    <note>In 2.0.0 specification, `org.osgi.service.permissionadmin` package is specified in chapter 4</note>
                </version>
            </package>
            <notes>
